# Generated by Django 2.2.4 on 2019-08-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagboard', '0003_auto_20190806_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTags',
            fields=[
                ('tagname', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
